version: '3'
volumes:
 data:
services:
  frontend:
    build: 
      context: frontend
      dockerfile: /Dockerfile
    restart: always
    ports:
      - "5173:80"
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456a@
      MYSQL_DATABASE: lotte_kiosk
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456a@
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"